version: "3"
services:
  app:
    image: invoice-cruiser-app
    container_name: invoice-cruiser-app
    ports:
      - 8000:8000
    volumes:
      - ./app:/opt/app
    command: python manage.py runserver 0.0.0.0:8000
  postgresql:
    image: postgres:10.5
    container_name: cruiser-postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mickey
      POSTGRES_PASSWORD: fantasy
      POSTGRES_DB: cruiser
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always